# Generated by Django 4.2.16 on 2024-11-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
