name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  DeployToProd:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:     
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          source: "."
          target: "/home/${{ secrets.DEPLOY_USERNAME }}/RivneITCard-API"

      - name: Delete old and run new container
        timeout-minutes: 4
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
              cd ~/RivneITCard-API
              chmod +x ./prod_startup.sh
              ./prod_startup.sh
