# docker-compose.yml
version: '3'
services:
  itcard_db_postgresql:
    restart: always
    container_name: itcard_db_postgresql
    image: postgis/postgis
    environment:
      - POSTGRES_DB=itcard
      - POSTGRES_USER=itcard
      - POSTGRES_PASSWORD=itcard
      - DEBUG=true
    ports:
      - "5432:5432"
    volumes:
      - pgsql:/var/lib/postgresql/data
  itcard_pga:
    container_name: itcard_db
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: volorymer7644@gmail.com
      PGADMIN_DEFAULT_PASSWORD: itcard
    ports:
      - "5050:80"
  redis:
    restart: always
    image: "redis:alpine"
    command: redis-server --requirepass redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis

    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  redis:
  pgsql: